### ISSUE TITLE
How to Two-way authentication?

### ISSUE THREAD

**Issue by Smiacter** [ThreeGayHub/SolarKit-Swift#3]
How to Two-way authentication? user xxx.cer and xxx.p12

**Comment by wyhazq** [comment]
内部暂时不支持双向认证，可以先重写sessionManager.delegate.taskDidReceiveChallenge来实现，可参考这个[链接](https://blog.csdn.net/codingfire/article/details/54376577)。
下个版本我再去封装和完善这部分功能。

**Comment by Smiacter** [comment]
好的，谢谢，我之前就是用的这个链接方法进行的双向认证，只不过当时直接用的Alamofire。期待你们的新版本😋

**Comment by wyhazq** [comment]
新版本已更新，1.0.5，[Target](https://github.com/ThreeGayHub/SolarNetwork/blob/master/Documentation/Target.md)，可以试一下。

**Comment by Smiacter** [comment]
嗯，明天验证下，我还有个问题，就是你们的传参可不可以像Moya一样通过Enum传入？比如我现在的get方法有参数是可变的，想通过Enum传入决定。但是看例子貌似都是写死的path，不知道是不是我看得不够仔细。

**Comment by Smiacter** [comment]
嗯，明天验证下，我还有个问题，就是你们的传参可不可以像Moya一样通过Enum传入？比如我现在的get方法有参数是可变的，想通过Enum传入决定。但是看例子貌似都是写死的path，不知道是不是我看得不够仔细。

**Comment by wyhazq** [comment]
所有子类Request的自定义属性都会反射成请求参数的，属性是var修饰的话就可以随便修改了，父类的默认参数也可以在外部修改，可以看下我刚刚提交的Reflection Demo，看一下HTTPBinPOSTRequest的用法

**Comment by Smiacter** [comment]
好的，谢谢，更新速度真快！以后有时间也来拜读下源码😀，不懂的向你们请教。

**Comment by Smiacter** [comment]
你好，我又遇到一个问题，post方法时，我定义反射属性与父类定义的相同，比如method，这种情况该如何处理？目前我是直接写在了parameters里面的

**Comment by wyhazq** [comment]
只能这样了......一般来说，叫后台别定义这种通用的字段

**Comment by Smiacter** [comment]
嗯，先这样，只是说没那么优雅。我调的是区块链的三方API，他们的post参数就有method这个参数名😂，是改不了的。
