### ISSUE TITLE
post如何传数组类型

### ISSUE THREAD

**Issue by Smiacter** [ThreeGayHub/SolarKit-Swift#4]
你好，目前暴露的只有parameters字典格式，当需要穿数组时该咋个处理？

**Comment by wyhazq** [comment]
1.0.7 fix.[Custom ParametersEncoding](https://github.com/ThreeGayHub/SolarNetwork/blob/master/Documentation/Request.md#custom-parameterencoding)

**Comment by Smiacter** [comment]
你好，感谢及时更新该问题，我在之前是用的Alamofire来传的数组。1.0.7的版本post传数组貌似可以了，但是之前版本1.0.5支持的HTTPs双向认证不起作用了，我跟了下clentTrustPolicy这个变量没有进入，麻烦看一下，谢谢啦。

**Comment by wyhazq** [comment]
意思是1.0.5https双向认证可以，1.0.7不行吗？断一下点看看是否进入这个分支？
`else if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
                return strongSelf.clientTrust(session: session, challenge: challenge)
            }`

**Comment by Smiacter** [comment]
是的，1.0.5可以，1.0.7不行。刚刚断点看了，
`else if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodClientCertificate {
                return strongSelf.clientTrust(session: session, challenge: challenge)
            }`这个分支是可以进的，但是进到里面的实现，`if let (secPKCS12Name, password) = self.target.clientTrustPolicy`不执行，也就是说self.target.clientTrustPolicy为nil，但是我在Target里面重写了这个变量 `var clentTrustPolicy: (secPKCS12Name: String, secPKCS12Password: String)? {
        return (secPKCS12Name: "client", secPKCS12Password: "xxxxxx")
    }` 原因应该就是这个变量没有附上值，1.0.5没问题

**Comment by wyhazq** [comment]
可以发个demo给我看一下吗？我这里没办法测试双重验证，麻烦发到邮箱：wyhazq@foxmail.com，你先用1.0.5的版本先。

**Comment by Smiacter** [comment]
你好，我也没有别的证书，只有一个用于正式项目的，暂时不方便发出来。

**Comment by wyhazq** [comment]
这就有点难办了，我想想办法搭个环境先。。。

**Comment by wyhazq** [comment]
我知道问题所在了，因为命名有点问题，我在1.0.6修改命名，所以你那里获取到的clientTrustPolicy为nil，你pod一下最新版本1.0.8，然后把命名修改为以下方式就能成功了
`var clientTrustPolicy: (secPKCS12Name: String, password: String)? {
        return (secPKCS12Name: "github", password: "123456")
    }`

**Comment by Smiacter** [comment]
好的，感谢，我下来试一下
