### ISSUE TITLE
更新httpheader

### ISSUE THREAD

**Issue by zhuaijunzaj** [ThreeGayHub/SolarKit-Swift#6]
你这个里面只能在初始化request 的时候设置header，没办法动态去更新，我现在有这样一个需求，token失效的时候，给httpheader设置另外一个参数，表示刷新token，我找了半天也没找到更新的方法，我想自己加，发现Alamofire 的Request 类里面的URLRequest 是只读，不允许修改，请问怎么解决

**Comment by wyhazq** [comment]
HTTP请求的header必须在请求发出去之前设置的，你接收到token失效了，代表你发出的请求已经结束了，重新new一个Request对象，加入header，重新发送请求即可。
