### ISSUE TITLE
request.resume()无效

### ISSUE THREAD

**Issue by zhuaijunzaj** [ThreeGayHub/SolarKit-Swift#7]
你好，目前在你的代码里发现两个问题，一个是我之前提到的没法动态更新httpHeader，还有一个是在plugin里拦截到一个错误的请求，重新设置好相应的参数，调resume方法无效，类似的代码如下：if response.apiStatus == 201630 {
            let loginData = LocalStorage.value(withkey: "loginInfo") as! NSDictionary
            let originHeader =  response.request?.headers as! NSMutableDictionary
            originHeader.removeObject(forKey: "Authorization")
            originHeader.setObject((loginData["Rmem-auth"] as! NSDictionary)["value"]!, forKey: "Rmem-auth" as NSString)
            response.request?.headers = (originHeader as! [String : String])
            response.request!.resume()}，希望能帮我一下，有什么解决方案没谢谢

**Comment by wyhazq** [comment]
resume和pause是成对使用的，分别调用的是Alamofire的resume和suspend，你在plugin里拦截到错误，代表请求已经结束了，建议你重新new一个该请求的对象，重新发起请求即可。
